Enable multiarch build, publish debs as container
tiiuae/PX4-msgs pull request #22
Opened 2024-10-24 11:35 UTC by mehmetkillioglu

## Changelog:
- Add amd64 and arm64 build support
- Push deb packages to `tiiuae/tii-px4-msgs`

2025-04-28 08:58 UTC, maseabunikie commented on .github/workflows/main.yaml
> +          docker create -ti --name "px4-msgs-build-temp-${{ matrix.architecture }}" --platform=linux/${{ matrix.architecture }} $(echo "${{ steps.meta.outputs.tags }}" | head -1) bash
Should we consider use ORAS to store the Debian package?
I don't know if on the consumer side makes it more difficult to use if the artifact is stored as OCI image.

2025-04-28 09:00 UTC, maseabunikie commented on Dockerfile
> +FROM ros:humble-ros-base as builder
What is the reason to not use the builder/SDK image?
We should use the SDK image so we will have aligned all the compiler and library versions used on runtime.

2025-04-28 09:03 UTC, maseabunikie commented on .github/workflows/main.yaml
> +          docker create -ti --name "px4-msgs-build-temp-${{ matrix.architecture }}" --platform=linux/${{ matrix.architecture }} $(echo "${{ steps.meta.outputs.tags }}" | head -1) bash
I don't know how we can manage this with multiarch images. It may be difficult or adding extra logic using tags with -arm64 or -amd64 suffixes.

2025-04-28 09:08 UTC, mehmetkillioglu commented on Dockerfile
> +FROM ros:humble-ros-base as builder
This builds will not be used for the containers that utilize the fog-ros-baseimage, but for the development environments. For instance, one can install this deb package (`ros-humble-px4-msgs`) in the local linux machine on amd64, ubuntu based Jetson (arm64), or a container with the ros:humble-ros-base build. Therefore, I replaced it to use the ros:humble-ros-base. The actual build in our system is still done with the yocto.

2025-04-28 09:11 UTC, maseabunikie commented on Dockerfile
> +FROM ros:humble-ros-base as builder
How can we document this?

2025-04-28 09:12 UTC, mehmetkillioglu commented on .github/workflows/main.yaml
> +          docker create -ti --name "px4-msgs-build-temp-${{ matrix.architecture }}" --platform=linux/${{ matrix.architecture }} $(echo "${{ steps.meta.outputs.tags }}" | head -1) bash
As these images are mainly to be used for development purposes, I figured the simple docker images would suffice. This would make the users just use the docker commands to fetch the deb packages to local pc or in the builds with Dockerfile. I assume the oras fetching needs a bit more elaborate steps to get this done, along with some more dependencies.

But it is a good point. We might possibly add the ORAS manifest pushing along with the docker images if needed.

2025-04-28 09:13 UTC, maseabunikie commented on README.md
> +### Copy and install deb packages in Dockerfile
Maybe document here what is the usage of the packages built in this repo.

2025-04-28 09:15 UTC, mehmetkillioglu commented on README.md
> +### Copy and install deb packages in Dockerfile
Yes, I was going to suggest the same place :+1:

I will wait for Jari's comments as well, then fix/add them together.

2025-04-28 09:35 UTC, jnippula requested changes

2025-04-28 09:35 UTC, jnippula commented on package.sh
> +bloom-generate rosdebian --os-name ubuntu --os-version jammy --ros-distro ${ROS_DISTRO} --place-template-files
I was thinking this Ubuntu Jammy version mentioned here, should it be here as a variable? Or does it even matter if we use jammy here while running on 24.04?

2025-04-29 11:10 UTC, mehmetkillioglu commented on package.sh
> +bloom-generate rosdebian --os-name ubuntu --os-version jammy --ros-distro ${ROS_DISTRO} --place-template-files
The ubuntu version actually comes from the `ros:humble-ros-base`, not the Github Action Runner. The Humble ROS2 docker images are with jammy. Iron and Rolling Ros releases are using the Noble.

2025-04-29 14:14 UTC, mehmetkillioglu commented on package.sh
> +bloom-generate rosdebian --os-name ubuntu --os-version jammy --ros-distro ${ROS_DISTRO} --place-template-files
I defined the os version as variable resolved from `/etc/os-release`, so it always matches the build environment. Then I went a bit further and enabled builds for humble and jazzy(next ROS2 LTS).

2025-05-05 09:46 UTC, maseabunikie approved these changes

2025-05-05 11:08 UTC, merged